---
- name: Playbook Examen
  hosts: webservers
  become: yes
  tasks:
  - name: Crear grupo
    group:
      name: user
      state: present
  - name: Crear usuario
    user:
      name: "{{usr}}"
      group: user
      password: '123'
      home: /users/"{{env}}"
  - name: Activar Include
    include: include.yml

  roles:
    - update
    - upgrade

...